[ufdbguard:filter:squid]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0
TIME_PREFIX = 
TIME_FORMAT = %Y-%m-%d %H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 100

# cleaning
SEDCMD-05_remove_extra_spaces = s/\s+/ /g

# EXTRACTS
# Extract all fields from ufdbguard logs
# ufdbguardd can log actions with PASS, BLOCK, REDIR, BPASS, BLOCK-LD and BLOCK-FATAL.
# 
# The log file contains lines that explain actions of ufdbguard: PASS, BLOCK, REDIR, BPASS, BLOCK-LD and BLOCK-FATAL.
# The log file may contain other lines that log the configuration, have additional information or debug data.
# 
# The lines where actions are logged are printed with a C-style format "%s [%d] %-5s %-16s %-15s %-10s %-13s %s %s %s %s" and contains
# - datetime: date and time
# 1. pid: process id
# 2. action: PASS, BLOCK, REDIR, BPASS, BLOCK-LD and BLOCK-FATAL
# 3. user: '-' or username
# 4. source: '-' or FQDN or IP
# 5. acl: which acl was used for the action
# 6. category: URL category, 'localnet' or 'any'
# 7. URL: the URL
# 8. HTTP method: GET/PUT/CONNECT etc.
# 9. SNI: usually void/empty; if ssl_bump mode is used, then for HTTP method 'CONNECT' this field contains the SNI if Squid sends the SNI to ufdbGuard
# 10. matchedby: contains which acl property triggered the action: ipv4-range, ipv4-subnet, ipv4-host, ipv6-net, ipv6-host, username, hostname, ip, default, loading-db or fatal-error

EXTRACT-ufdbguard-filter = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\s+\[(?<process_id>\d+)\]\s+(?<decision>(PASS|BLOCK|REDIR|BPASS|BLOCK-LD|BLOCK-FATAL))\s+(?<user>\S+)\s+(?<src>\S+)\s+(?<acl>\S+)\s+(?<category>\S+)\s+(?<url>\S+)\s+(?<http_method>\S+)\s+((?<sni>\S+)\s+)?(?<matchedby>\S+)$

# REPORTS
REPORT-ufdbguard_url_parsing = ufdbguard_parse_url

# Field aliases for CIM compliance

# Calculated fields
EVAL-action = if((decision=="PASS" OR decision=="BPASS"), "allowed", blocked")
EVAL-src = if(src!="-", src, null())
EVAL-user = if(user!="-", user, null())
EVAL-vendor_product = "ufdbguard"
